openapi: 3.0.4
info:
  version: '1.0'
  title: "HikeNest OpenAPI 1.0"
  description: API built to manage group hikes.
  license:
    name: MIT
servers:
  - url: http://localhost:8080/api/v1
    description: Localhost
  - url: http://questositononesiste.com
    description: da cambiare in fase di deploy
paths: 
  /authentication:
    post:
      summary: Autenticazione di un utente
      description: Autentica uno user creando un token di sessione JWT
      responses:
        '200' :
          description: Token creato
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: True se l'utente è riuscito ad autenticarsi
                  token:
                    type: string
                    description: Token di autenticazione
        '401' : 
          description: Credenziali sbagliate
      requestBody:
        description: Nel body devono essere presenti username e password
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required:
                - mail
                - password
              properties:
                mail:
                  type: string
                  description: Mail dell'utente
                password: 
                  type: string
                  description: Password dell'utente
  /register:
    post:
      summary: Crea un utente con email, username e password
      description: È possibile creare un utente inviando username, email e password al sistema
      requestBody:
        description: Nel body devono essere presenti username, mail e password
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - mail
                - password 
                - username
              properties:
                mail:
                  type: string
                  format: email
                  description: Indirizzo email dell'utente
                password:
                  type: string
                  description: Password dell'utente
                username: 
                  type: string
                  description: Username scelto dall'utente

      responses:
        '201':
          description: Utente creato!
          content:  
            application/json:
              schema: 
                type: object
                properties:
                  self:
                    type: string
                    description: Link alla nuova risorsa
        '400': 
          description: Errore nella creazione dell'utente

          
  /gruppi:
    get:
      summary: Lista dei gruppi
      description: Ottieni la lista di tutti i gruppi, per ottenerne uno solo usa /gruppi/{IDgruppo}
      responses:
        '200':
          description: Lista dei gruppi
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Gruppo'
    post:
      summary: Crea un nuovo gruppo
      description: Creazione di un nuovo gruppo inviando i dati necessari
      requestBody:
        description: Nella richiesta vanno inseriti tutti i dati relativi al gruppo
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Gruppo"
      responses: 
        '201':
          description: Gruppo creato
          headers: 
            location:
              schema:
                type: string
              description: Link al nuovo gruppo
        '401': 
          description: Utente non autenticato
        '400': 
          description: Dati invalidi
      
    
    
  /gruppi/{IDGruppo}:
    get:
      summary: Pagina di un gruppo
      description: Ottieni informazioni riguardo un singolo gruppo
      parameters:
        - in : path
          name: IDGruppo
          required: true
          schema: 
            type: string
          description: ID del gruppo
      responses:
        '200':
          description: Gruppo trovato
          content:  
            application/json:
              schema:
                $ref: "#/components/schemas/Gruppo" 
        '404':
          description: Gruppo non trovato
        '401': 
          description: Utente non autenticato
  
  /percorsi:
    get:
      summary: Lista di tutti i percorsi
      description: Ottieni la lista completa di tutti i percorsi, eventualmente filtrati per lunghezza
      parameters:
      - in: query #usiamo query per fare /percorsi?minKm=1&maxKm=100 invece che path che consente un solo param
        name: minKm
        schema:
          type: number
          format: float
        required: false
        description: Lunghezza minima del percorso in km
      - in: query
        name: maxKm
        schema:
          type: number
          format: float
        required: false
        description: Lunghezza massima del percorso in km
      responses:
        '200':
          description: Lista dei percorsi
          content: 
            application/json:
              schema:
                type: array
                items : 
                  $ref: "#/components/schemas/Percorso"
        '401': 
          description: Utente non autenticato

  /percorsi/{idPercorso}/recensioni:
    get:
      summary: Lista delle recensioni di un percorso
      description: Restituisce una lista contenente tutte le recensioni di un singolo percorso
      parameters:
      - in: path
        name: idPercorso
        required: true
        schema:
          type: string
          description: Id del percorso dal quale cercare le recensioni
      responses:
        '200':
          description: Lista delle recensioni trovate
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Recensione'
        '401': 
          description: Utente non autenticato
    post:
      summary: Crea una nuova recensione
      description: Permette ad un utente di creare una nuova recensione 
      parameters:
      - in: path
        name: idPercorso
        required: true
        schema:
          type: string
          description: Id del percorso del quale inserire una recensione
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Recensione'
      responses:
        '201':
          description: Recensione creata
        '400':
          description: Dati forniti non validi
        '401': 
          description: Utente non autenticato

  /percorsi/{idPercorso}/segnalazioni:
    get:
      summary: Lista delle segnalazioni relative ad un percorso
      description: Restituisce la lista di tutte le segnalazioni fornite rispetto ad un percorso
      parameters:
      - in: path
        name: idPercorso
        required: true
        schema:
          type: string
          description: Id del percorso dal quale cercare le segnalazioni
      responses:
        '200':
          description: Lista delle segnalazioni trovate
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Segnalazione'
        '401': 
          description: Utente non autenticato
    post:
      summary: Inviare una nuova segnalazione
      description: Permette ad un utente di inviare una segnalazione relativa ad una problematica su un percorso
      parameters:
      - in: path
        name: idPercorso
        required: true
        schema:
          type: string
          description: Id del percorso menzionato nella segnalazione
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Segnalazione'
      responses:
        '201':
          description: Segnalazione registrata
        '400':
          description: Dati forniti non validi
        '401': 
          description: Utente non autenticato

        


  /join:
    post: 
      summary: Aggiunta di un utente ad un gruppo
      description: Un utente viene aggiunto ad un gruppo già esistente, inviando la sua mail
      requestBody: 
        content:
          application/json:
            schema:
              type: object
              required:
                - mail
                - idGruppo
              properties: 
                  mail:
                    type: string
                    description: Mail dell'utente da aggiungere al gruppo
                  idGruppo:
                    type: string
                    description: ID del gruppo da joinare
      responses: 
        '201':  
          description: Utente aggiunto
        '400':
          description: Impossibile aggregarsi al gruppo, azione fallita
        '401': 
          description: Utente non autenticato

  

  

components: 
  schemas:
  #usa questo schema per restituire uno/più gruppi quando l'utente li richiede
    Gruppo:
      type: object
      required: 
        - nome
        - idPercorso
        - esperienza
        - data
      properties:
        self:
          type: string
          description: "Link al gruppo"
        nome:
          type: string
          description: "Nome del gruppo"
        idPercorso:
          type: string
          description: "Id del percorso associato al gruppo"
        esperienza:
          type: string
          enum : [neofita, medio, esperto]
          description: "Livello di esperienza consigliato a chi partecipa"
        data:
          type: string
          format: date-time
          description: "Data in cui si effettura l'hike"


  #schema unico per i percorsi
    Percorso:
      type: object
      required:
        - nome
        - difficolta
        - lunghezzaKm
      properties:
        self:
          type: string
          description: Link al percorso
        nome:
          type: string
          description: Nome del percorso
        lunghezzaKm:
          type: number
          format: float
          description: Lunghezza complessiva in chilometri
        difficolta: 
          type: string
          enum: [facile, medio, difficile]
          description: Livello di difficolta del percorso

    Recensione:
      type: object
      required: 
        - idPercorso
        - idUtente
        - testo
        - valutazione
      properties:
        self:
          type: string
          description: Link alla recensione
        idPercorso:
          type: string
          description: Id del percorso a cui è associata la recensione
        idUtente:
          type: string
          description: Id dell'utente che ha postato la recensione
        testo: 
          type: string
          description: Testo facente parte della recensione
        valutazione: 
          type: number
          minimum: 1
          maximum: 5
          description: Valore numerico lasciato dall'utente in valutazione al percorso
    
    Segnalazione:
      type: object
      required: 
        - idPercorso
        - idUtente
        - testo
      properties:
        self:
          type: string
          description: Link alla segnalazione
        idPercorso:
          type: string
          description: Id del percorso associato alla segnalazione
        idUtente:
          type: string
          description: Id dell'utente che ha aperto la segnalazione
        testo:
          type: string
          description: Descrizione associata alla segnalazione
